adds signature endpoint
massalabs/thyra-plugin-massa-core pull request #2
Opened 2022-11-28 11:25 UTC by gregLibert

2022-11-28 11:40 UTC, Trottoir reviewed
CI KO :'(

2022-11-28 13:15 UTC, Thykof commented
It looks like copypasta from Thyra, have we planned to remove this from Thyra?

2022-11-28 15:41 UTC, gregLibert commented
> CI KO :'(

Fixed

2022-11-28 15:42 UTC, gregLibert commented
> It looks like copypasta from Thyra, have we planned to remove this from Thyra?

That's part of the plan. I will let you have a discussion with @SlnPons on that :-)

2022-12-01 19:42 UTC, gregLibert commented
@Thykof @Trottoir @peterjah where are we on this topic?

2022-12-02 09:43 UTC, Thykof requested changes

2022-12-02 09:43 UTC, Thykof commented on .github/workflows/CI.yml
> +          path: thyra-server_${{ matrix.target }}_${{ matrix.arch }}
really? it might be `thyra-plugin_massa-core_`?

2022-12-02 14:09 UTC, peterjah requested changes

2022-12-02 14:09 UTC, peterjah commented on api/server/resource/swagger.yml
> +      publicKey:
its a bit strange that the public key is returned here.. it will be used to check if the signature has been made with the good one ? if yes maybe it it would be better to call signOperation directly with the publickey instead of the wallet nickname.
but i guess its another issue !

2022-12-02 14:18 UTC, gregLibert commented on api/server/resource/swagger.yml
> +      publicKey:
No, it's a field expected by the node.
When you interact with the wallet plugin, you identify the keypair you want to use by it's nickname (who can remember is public key ?).
Then, when the wallet answer, it gives you all the information you need regarding the wallet to send the command to node.

2022-12-02 14:19 UTC, gregLibert commented on .github/workflows/CI.yml
> -          path: thyra-plugin_massa-core_${{ matrix.target }}_${{ matrix.arch }}
I don't understand

2022-12-02 14:40 UTC, peterjah commented on api/server/resource/swagger.yml
> +      publicKey:
> No, it's a field expected by the node.

ok but it is not question of the node here only thyra <=> plugin 

> who can remember is public key ?. 

the question is not about remembering, imho it will be cleaner if the nickname is used only by the frontend to link with a publicKey or address, and the wallets should be indexed by publicKey because its unique

> Then, when the wallet answer, it gives you all the information you need regarding the wallet to send the command to node.

thats mean when you request the signature, you are not sure of the corresponding wallet who will be used? its seems adventurous

2022-12-02 15:25 UTC, gregLibert commented on api/server/resource/swagger.yml
> +      publicKey:
> ok but it is not question of the node here only thyra <=> plugin

When is operation is signed you will send it to the node for execution. This is not done by the plugin of the wallet.

> the question is not about remembering, imho it will be cleaner if the nickname is used only by the frontend to link with a publicKey or address, and the wallets should be indexed by publicKey (or addresss) because its unique and the format is restricted

Who will store the nickname? => the wallet
What the enduser uses to sign a transaction? => the nickname

Therefore the wallet receive a request to sign with the private key linked to the given nickname.

> thats mean when you request the signature, you are not sure of the corresponding wallet who will be used? its seems adventurous

I don't understand.
Let's have a call:-)

2022-12-02 15:26 UTC, gregLibert commented on .github/workflows/CI.yml
> -          path: thyra-plugin_massa-core_${{ matrix.target }}_${{ matrix.arch }}
Solved, thx!

2022-12-06 09:07 UTC, merged

2022-12-06 10:15 UTC, SlnPons commented
Hey @peterjah , @gregLibert  can you confirm that I can't test this until the plug-in manager side is done on thyra?
If no and so I can test this issue, could you explain me how please?

2022-12-06 11:07 UTC, gregLibert commented
> Hey @peterjah , @gregLibert can you confirm that I can't test this until the plug-in manager side is done on thyra? If no and so I can test this issue, could you explain me how please?

No, you can directly interact with its API without waiting for the plug-in manager. We can organize a call on that.